name: Full Cycle CI Practice

on:
  pull_request:
jobs:
  sonarque_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy NodeJS 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - run: yarn
      - run: yarn test:coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
